### PR TITLE
Create a very simple liveness check

### PR DESCRIPTION
**Pull request by garthwilliamson**
For Kubernetes, it's good to have two checks on a site - if the container is alive (i.e. not hung) and if the container is ready (can connect to database etc).

### CODE REVIEW

**Comment by brendanheywood** [comment]
@garthwilliamson this should already be covered? This is the difference between index.php vs croncheck.php 

The naming of the files is a bit crap due to history but you can read about the intent here:

https://github.com/catalyst/moodle-tool_heartbeat#front-end-health

What use case do you have that isn't covered by either of those two?

**Comment by brendanheywood** [comment]
vs:

https://github.com/catalyst/moodle-tool_heartbeat#application-health

**Comment by brendanheywood** [comment]
also random fyi, my plan is for this plugin to die at some point, see also:

https://tracker.moodle.org/browse/MDL-67818

**Comment by garthwilliamson** [comment]
@brendanheywood I need to check this again with the newer version - at least before, it required wwwroot to match which wasn't very useful
It also caused pods to cycle badly when the site wasn't yet installed, I'm not sure why this was looking at the current code. Maybe that's also fixed now.

**Comment by garthwilliamson** [comment]
Hi Brendan,

Index.php pulls in config.php and connects to the database. For a kubernetes liveness probe, we need a much more basic check - essentially just that the apache is running.

When a liveness probe fails, it has to be assumed that the container is really broken, for example out of memory, crashed or something else like this. So kuberenetes will immediately destroy the container.

A healthcheck on the other hand is used to check that the application itself is ok. It ensures that it can talk to all the backend systems etc. Healthchecks are used to add things to the load balancers. If a healthcheck fails, that pod is removed from the loadbalancer until it becomes healthy again.

Cheers,
Garth

**Comment by garthwilliamson** [comment]
The problem we were running into might have also been due to something else happening in config.php, not the database, I have to recheck this.

**Comment by brendanheywood** [comment]
@garthwilliamson this new file is pretty trivial, its almost so trivial I'm wondering why you'd even want this inside a moodle plugin as it has nothing to do with moodle? We have a file like this but its part of the container templates.

Is there any special meaning to the 'php is ALIVE' ? Ours is simply echos "OK" so I'd be looking for something reasonably generic

**Comment by garthwilliamson** [comment]
Hi Brendan, You're right, I didn't even really think to have it separately,
but of course that'll work, and we can easily do it as part of the
container template or similar. Thanks!
Cheers
Garth

**Pull request closed without merging**
